0016451: Daily build not successful Fix to build error in release config found when building from rev 3664: ImportCamcorderWindow.xaml.cs(619,22): error CS0161: 'ImportCamcorderDll.ImportCamcorderWindow.CheckFolderAccessLevel(string)': not all code paths return a value Just added return false at the end of the function.   The error is possibly the reason there was no build this morning.