0024276: S00543_Kinetic 0025434: [S00543_Kinetic] Kinetic style does not have the Film color super style options that all other default styles do
(merged trunk@15657 -> Anderson_BR2_branch)

Fixed lots of minor issues introduced when film color was integrated into existing the Kinetic effects. Also took this opportunity to do a massive code clean-up. Full gory details as follows.

Issue: Darker captions shadow on first scene segment.
Affected: corners-join-and-split, deck-of-cards, fly-out, horizontal-strips-wobble, diagonal-slices, eclipse, multi-sliding-sections, vertical-strips-bounce, three-slices-crisscross, four-slices-crisscross, oscillate-flip, twist-and-split, puzzle, radiate

Issue: Darker captions shadow on overlapping TextureSubset regions.
Affected: vertical-strips-bounce, four-slices-crisscross, three-slices-crisscross, puzzle

Issue: Captions shown momentarily in a different color.
Affected: halftone, tiled-normal-hover, tiled-windmill

Issue: Failed to dim brightness of supplementary inputs.
Affected: carousel-stacks-hover-slide, constellation

Issue: Gradient wipe direction is reversed.
Affected: tiled-normal-hover, tiled-windmill

To improve aesthetics of captions, the behavior is modified as follows:

Enhanced: Captions fade in and fade out of segments.
Affected: carousel-spin-bounce, constellation, scattered, gallery-bounce-rotate, gallery-hop, etc.

Enhanced: Only one caption layer per active segment. Not shown in repeated segments.
Affected: constellation, carousel-stack-hover-slide, oscillate-flip, cogwheel-rotate, radiate, etc.
Exception: deck-of-cards (due to technical reasons)


Conflicts:

	_CommonModules/Constructor/muveeStyles/muse/scene.scm